# Generated by Django 3.2.5 on 2023-01-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название категории блюда')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Публикуемые')),
            ],
            options={
                'verbose_name': 'Категория блюда',
                'verbose_name_plural': 'Категории блюд',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание блюда')),
                ('price', models.IntegerField(verbose_name='Цена блюда')),
                ('is_special', models.BooleanField(default=False, verbose_name='Особое блюдо')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Вегитарианское блюдо')),
                ('is_publish', models.BooleanField(default=True, verbose_name='Публикуемое блюдо')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_list.foodcategory', verbose_name='Категория блюда')),
                ('topping', models.ManyToManyField(blank=True, related_name='topping', to='menu_list.Topping', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
