# Generated by Django 3.2.5 on 2023-01-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='topping',
        ),
        migrations.CreateModel(
            name='ToppingFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_list.food', verbose_name='Блюдо')),
                ('topping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_list.topping', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Связь блюдо - ингредиент',
                'verbose_name_plural': 'Связи блюда - ингредиенты',
            },
        ),
    ]
