# Generated by Django 3.2.5 on 2023-01-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_list', '0002_auto_20230120_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='menu_list.foodcategory', verbose_name='Категория блюда'),
        ),
    ]
