# Generated by Django 3.2.5 on 2023-01-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_list', '0005_auto_20230124_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='topping',
            field=models.ManyToManyField(to='menu_list.Topping', verbose_name='Ингредиенты'),
        ),
        migrations.DeleteModel(
            name='ToppingFood',
        ),
    ]
